runner:
  total_steps: 40000
  gradient_clipping: 5
  gradient_accumulate_steps: 1

  log_step: 100
  eval_step: 250
  save_step: 500
  max_keep: 1
  eval_dataloaders:
    - dev
    - test

optimizer:
  name: Adam
  lr: 1.0e-4

# comment the whole scheduler config block
# to disable learning rate scheduling
scheduler:
  name: linear_schedule_with_warmup
  num_warmup_steps: 2000

downstream_expert:
  datarc:
    num_workers: 8
    train_batch_size: 16
    eval_batch_size: 24
    file_path: /livingrooms/public/VCC_2018

  modelrc:
    projector_dim: 256
    clipping: True # If true, the model output will be restrict to the interval [1,5] using Tanh
    attention_pooling: False
