default_language_version:
  python: python3

files: |
  (?x)(
    ^s3prl/nn/|
    ^s3prl/base/|
    ^s3prl/util/|
    ^s3prl/task/|
    ^s3prl/metric/|
    ^s3prl/corpus/|
    ^s3prl/encoder/|
    ^s3prl/dataset/|
    ^s3prl/preprocessor/|
    ^test/|
    ^example/
  )

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: trailing-whitespace
        types: [python]
      - id: end-of-file-fixer
        types: [python]
      - id: mixed-line-ending
        types: [python]
        args: [--fix=no]
      - id: check-added-large-files
        args: [--maxkb=1024]
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3.8
        types: [python]
        additional_dependencies: ['click==8.0.4']
  - repo: https://gitlab.com/pycqa/flake8.git
    rev: 3.9.2
    hooks:
      - id: flake8
        types: [python]
        args: [
          "--select=E9,F63,F7,F82",
        ]
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        exclude: README.md
        additional_dependencies: [toml]
        args: ["--profile", "black"]
