runner:
  total_steps: 50000
  gradient_clipping: 5
  gradient_accumulate_steps: 4

  log_step: 100
  eval_step: 250
  save_step: 500
  max_keep: 1
  eval_dataloaders:
    - dev
    - test

optimizer:
  name: Adam
  lr: 5.0e-5

# comment the whole scheduler config block
# to disable learning rate scheduling
scheduler:
  name: linear_schedule_with_warmup
  num_warmup_steps: 2000

downstream_expert:
  datarc:
    num_workers: 8
    train_batch_size: 4
    eval_batch_size: 4
    file_path: /groups/public/VCC_2018

  modelrc:
    projector_dim: 768