name: build

on:
  # Trigger the workflow on push to main or any pull request
  push:
    branches:
      - main
  pull_request:

jobs:
  build:

    strategy:
      max-parallel: 4
      matrix:
        platform: [ubuntu-latest]
        python-version: [3.8, 3.9]
        torchaudio-version: [0.10.0, 0.9.1, 0.8.2]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Upgrade pip
      run: pip3 install --upgrade pip

    - name: Install PyTorch & Torchaudio
      run: pip3 install torchaudio==${{ matrix.torchaudio-version }}

    - name: Install S3PRL
      run: pip3 install --editable ".[all]"

    - name: Check coding style by ci/format.sh
      run: |
        ./ci/format.sh

    - name: Run tests
      run: |
        pytest
