name: CI

on:
  # Trigger the workflow on push to main or any pull request
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:

    strategy:
      max-parallel: 4
      matrix:
        extra: [none, all]
        os: [ubuntu-18.04]
        python-version: [3.8]
        torchaudio-version: [0.8.1, 0.9.1, 0.10.2, 0.11.0, 0.12.1]
        include:
          - os: ubuntu-20.04
            python-version: 3.7
            torchaudio-version: 0.11.0
          - os: ubuntu-20.04
            python-version: 3.9
            torchaudio-version: 0.8.1

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Check coding style by ci/format.py
      run: |
        ./ci/format.py --check

    - name: Install Linux dependencies
      run: sudo apt-get install -y libsndfile1-dev sox git git-lfs

    - name: Upgrade pip and wheel
      run: pip3 install --upgrade pip wheel

    - name: Install S3PRL basic
      if: ${{ matrix.extra == 'none' }}
      run: pip3 install -e "./"

    - name: Install S3PRL all
      if: ${{ matrix.extra == 'all' }}
      run: pip3 install -e ".[all]"

    - name: Install specific PyTorch & Torchaudio
      run: pip3 install torchaudio==${{ matrix.torchaudio-version }}

    - name: Install dependencies for tests
      run: pip3 install pytest pytest-xdist python-dotenv

    # This can be very helpful for debugging
    # The action can create a SSH server for you to connect. After you
    # log into the machine hosted by GitHub, it becomes easy to debug
    # why the CI fails on a specific machine.

    # - name: Setup upterm session
    #   uses: lhotari/action-upterm@v1

    - name: Run tests for common upstream
      if: ${{ matrix.extra == 'none' }}
      run: |
        pytest test/test_upstream.py --runupstream -n 2

    - name: Run tests for all s3prl functions except upstream
      if: ${{ matrix.extra == 'all' }}
      run: |
        pytest --runslow -n 2
